import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
    <Navbar />
      <Head>
        <title>HelpMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <section className={styles.sectionInfo}>
          <h1 className={styles.title}>HOME REPAIR</h1>
          <h2 className={styles.subtitle}>& Renovating</h2>
          <p className={styles.paragraph}>
            Cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
            cupidatat non proident, sunt in culpa qui officia deserunt mollit
            anim id est laborum.
          </p>
        </section>
        <section className={styles.sectionImg}>
          <Image
            src="/img/imgHome.png"
            width={450}
            height={674}
            alt="Imagen Home"
          ></Image>
          <p>
            Sample text. Lorem ipsum dolor sit amet, consectetur adipiscing elit
            nullam nunc justo sagittis suscipit ultrices.
          </p>
        </section>
      </div>
      <div className={styles.content}>
        <section className={styles.homeCleaning}>
          <div className={styles.homeCleaning__img}>
            <Image
              src="/img/sweeping.png"
              width={78}
              height={78}
              alt="Imagen Home"
            ></Image>
          </div>
          <div className={styles.homeCleaning__title}>
            <h5>HOME CLEANING</h5>
          </div>
          <div className={styles.homeCleaning__paragraph}>
            <p>
              Sample text. Lorem ipsum dolor sit amet, consectetur adipiscing
              elit nullam nunc justo sagittis suscipit ultrices.
            </p>
          </div>
        </section>
        <section className={styles.smartHome}>
          <div className={styles.smartHome__img}>
            <Image
              src="/img/smart-bulb.png"
              width={78}
              height={78}
              alt="Imagen Home"
            ></Image>
          </div>
          <div className={styles.smartHome__title}>
            <h5>SMART HOME</h5>
          </div>
          <div className={styles.smartHome__paragraph}>
            <p>
              Sample text. Lorem ipsum dolor sit amet, consectetur adipiscing
              elit nullam nunc justo sagittis suscipit ultrices.
            </p>
          </div>
        </section>
        <section className={styles.interiorPaintin}>
          <div className={styles.interiorPaintin__img}>
            <Image
              src="/img/paint-roller.png"
              width={78}
              height={78}
              alt="Imagen Home"
            ></Image>
          </div>
          <div className={styles.interiorPaintin__title}>
            <h5>INTERIOR PAINTIN</h5>
          </div>
          <div className={styles.interiorPaintin__paragraph}>
            <p>
              Sample text. Lorem ipsum dolor sit amet, consectetur adipiscing
              elit nullam nunc justo sagittis suscipit ultrices.
            </p>
          </div>
        </section>
        <section className={styles.lightFixures}>
          <div className={styles.lightFixures__img}>
            <Image
              src="/img/home.png"
              width={78}
              height={78}
              alt="Imagen Home"
            ></Image>
          </div>
          <div className={styles.lightFixures__title}>
            <h5>LIGHT FIXTURES</h5>
          </div>
          <div className={styles.lightFixures__paragraph}>
            <p>
              Sample text. Lorem ipsum dolor sit amet, consectetur adipiscing
              elit nullam nunc justo sagittis suscipit ultrices.
            </p>
          </div>
        </section>
      </div>
      <section className={styles.about}>
        <div className={styles.about__title}>
          <h1>About Us</h1>
        </div>
        <div className={styles.about__paragraph}>
          <p>
            Oh feel if up to till like. He an thing rapid these after going
            drawn or. Timed she his law the spoil round defer. In surprise
            concerns informed betrayed he learning is ye. Ignorant formerly so
            ye blessing. He as spoke avoid given downs money on we. Of properly
            carriage shutters ye as wandered up repeated moreover.
          </p>
        </div>
        <div className={styles.about__button}>
          <a>LEARN MORE</a>
        </div>
      </section>
    </div>
  );
}
