import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import Swal from "sweetalert2";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.scss";

export default function Home() {

  const { data: session, status } = useSession();
  const router = useRouter();

  if (status === "loading") {
    return (
      <div className={styles.container}>
        <h1>Loading...</h1>
      </div>
    );
  }

  const signUpProfessional = () => {
    router.push("/sign-up/professional");
  };

  const routerElectrician = () => {
    if (session) {
      router.push("services-home/electrician");
    } else {
      router.push("/login/client");
    }
  };

  const routerBuilder = () => {
    if (session) {
      router.push("services-home/builder");
    } else {
      router.push("/login/client");
    }
  };

  const routerSmartHome = () => {
    if (session) {
      router.push("services-home/automation");
    } else {
      router.push("/login/client");
    }
  };

  const routerAppliances = () => {
    if (session) {
      router.push("services-home/appliances");
    } else {
      router.push("/login/client");
    }
  };

  const handleLoginPro = () => {
    if(session){
      Swal.fire({
        title: "Invalid!",
        text: "Please, sign out your account client.",
        icon: "error",
        confirmButtonText: "ok",
      });
    }else{
      router.push("/login/professional")
    }
  }
  return (
    <div className={styles.container}>
     <Navbar/>
      <Head>
        <title>HelpMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <section className={styles.sectionInfo}>
          <h1 className={styles.title}>HOME REPAIR</h1>
          <h2 className={styles.subtitle}>& Renovating</h2>
          <p className={styles.paragraph}>
            We create a network of professionals close to your home to take care
            of your problems at home. You can see their experience and the
            qualifications they have obtained in other jobs.
          </p>
        </section>
        <section className={styles.sectionImg}>
          <Image
            src="/img/imgHome.png"
            width={450}
            height={674}
            alt="Imagen Home"
          ></Image>
        </section>
      </div>
      <div className={styles.content}>
        <button className={styles.homeCleaning} onClick={routerAppliances}>
          <div className={styles.homeCleaning__img}>
            <Image
              src="/img/electrodo.png"
              width={78}
              height={78}
              alt="Imagen Home"
            ></Image>
          </div>
          <div className={styles.homeCleaning__title}>
            <h5>HOME APPLIANCE REPAIR</h5>
          </div>
          <div className={styles.homeCleaning__paragraph}>
            <p>
              Repair of TVs, refrigerators, washing machines and any other
              appliances you have at home.
            </p>
          </div>
        </button>
        <button className={styles.smartHome} onClick={routerSmartHome}>
          <div className={styles.smartHome__img}>
            <Image
              src="/img/smart-bulb.png"
              width={78}
              height={78}
              alt="Imagen Home"
            ></Image>
          </div>
          <div className={styles.smartHome__title}>
            <h5>SMART HOME</h5>
          </div>
          <div className={styles.smartHome__paragraph}>
            <p>
              Smart home design and installation. Connection and configuration
              problems
            </p>
          </div>
        </button>
        <button className={styles.interiorPaintin} onClick={routerBuilder}>
          <div className={styles.interiorPaintin__img}>
            <Image
              src="/img/paint-roller.png"
              width={78}
              height={78}
              alt="Imagen Home"
            ></Image>
          </div>
          <div className={styles.interiorPaintin__title}>
            <h5>HOME REPAIR</h5>
          </div>
          <div className={styles.interiorPaintin__paragraph}>
            <p>
              Structural troubleshooting, plumbing, painting. Remodeling of
              complete spaces
            </p>
          </div>
        </button>
        <button className={styles.lightFixures} onClick={routerElectrician}>
          <div className={styles.lightFixures__img}>
            <Image
              src="/img/home.png"
              width={78}
              height={78}
              alt="Imagen Home"
            ></Image>
          </div>
          <div className={styles.lightFixures__title}>
            <h5>ELECTRICAL PROBLEMS</h5>
          </div>
          <div className={styles.lightFixures__paragraph}>
            <p>
              New electrical connections, light problems inside the house or
              modifications of light cables.
            </p>
          </div>
        </button>
      </div>
      <section className={styles.about}>
        <div className={styles.about__title}>
          <h1>About Us</h1>
        </div>
        <div className={styles.about__paragraph}>
          <p>
            We are a network of technicians, professionals and small independent
            companies that seek to provide faster services and solutions to
            people in their homes. Achieving that independent workers get more
            work. If you want to be part of this network and be known in your
            area, start your registration so that hundreds of people can call
            you and hire you.
          </p>
        </div>
        <button className={styles.about__button} onClick={signUpProfessional}>
          <a>Register Form</a>
        </button>
        <div className={styles.about__login}>
          <p>
            Already have an account?{" "}
            <button onClick={handleLoginPro}>
              Login
            </button>
          </p>
        </div>
      </section>
      <Footer />
    </div>
  );
}
